"""corrected unit names

Revision ID: 0b69e6a1fd70
Revises: 15b46b1502d3
Create Date: 2019-02-02 15:39:58.415917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b69e6a1fd70'
down_revision = '15b46b1502d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_predictions', sa.Column('u_unit', sa.String(length=255), nullable=True))
    op.drop_column('candidate_predictions', 'u_unit_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_predictions', sa.Column('u_unit_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('candidate_predictions', 'u_unit')
    # ### end Alembic commands ###
