"""let's make another try

Revision ID: 3a532c08bf79
Revises: 
Create Date: 2019-02-02 14:24:29.550560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a532c08bf79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('e_id', sa.Integer(), nullable=False),
    sa.Column('e_name', sa.String(length=255), nullable=True),
    sa.Column('e_age', sa.Integer(), nullable=True),
    sa.Column('e_gender', sa.Integer(), nullable=True),
    sa.Column('e_recomended', sa.Integer(), nullable=True),
    sa.Column('e_position_eng', sa.String(length=255), nullable=True),
    sa.Column('e_salary_base', sa.Integer(), nullable=True),
    sa.Column('e_recruiter', sa.String(length=255), nullable=True),
    sa.Column('e_days_to_hire', sa.Integer(), nullable=True),
    sa.Column('e_commute', sa.Float(), nullable=True),
    sa.Column('e_entrance_type', sa.Integer(), nullable=True),
    sa.Column('e_source', sa.String(length=255), nullable=True),
    sa.Column('e_date_entered', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('e_id')
    )
    op.create_table('recruiters',
    sa.Column('r_id', sa.String(length=255), nullable=False),
    sa.Column('e_recruiter', sa.String(length=255), nullable=True),
    sa.Column('r_age', sa.Integer(), nullable=True),
    sa.Column('r_tenure', sa.Integer(), nullable=True),
    sa.Column('r_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('r_id')
    )
    op.create_table('candidate_predictions',
    sa.Column('p_id', sa.Integer(), nullable=False),
    sa.Column('e_id', sa.Integer(), nullable=False),
    sa.Column('e_position_eng', sa.String(length=255), nullable=True),
    sa.Column('e_salary_base', sa.Integer(), nullable=True),
    sa.Column('u_department', sa.String(length=255), nullable=True),
    sa.Column('u_unit', sa.String(length=255), nullable=True),
    sa.Column('u_ntt', sa.Integer(), nullable=True),
    sa.Column('e_age', sa.Integer(), nullable=True),
    sa.Column('e_gender', sa.Integer(), nullable=True),
    sa.Column('u_tl_tenure', sa.Integer(), nullable=True),
    sa.Column('u_tl_age', sa.Integer(), nullable=True),
    sa.Column('u_tl_gender', sa.Integer(), nullable=True),
    sa.Column('u_hires_week', sa.Integer(), nullable=True),
    sa.Column('u_exits_week', sa.Integer(), nullable=True),
    sa.Column('u_hires_month', sa.Integer(), nullable=True),
    sa.Column('u_exits_month', sa.Integer(), nullable=True),
    sa.Column('u_headcount', sa.Integer(), nullable=True),
    sa.Column('u_age_mean', sa.Float(), nullable=True),
    sa.Column('u_tenure_mean', sa.Float(), nullable=True),
    sa.Column('u_gender_average', sa.Float(), nullable=True),
    sa.Column('e_entrance_type', sa.Integer(), nullable=True),
    sa.Column('e_source', sa.String(length=255), nullable=True),
    sa.Column('e_days_to_hire', sa.Integer(), nullable=True),
    sa.Column('e_recomended', sa.Integer(), nullable=True),
    sa.Column('r_age', sa.Integer(), nullable=True),
    sa.Column('r_tenure', sa.Integer(), nullable=True),
    sa.Column('r_level', sa.Integer(), nullable=True),
    sa.Column('u_tl_active', sa.Integer(), nullable=True),
    sa.Column('e_commute', sa.Float(), nullable=True),
    sa.Column('u_department_B2B', sa.Integer(), nullable=True),
    sa.Column('u_department_Shift_1', sa.Integer(), nullable=True),
    sa.Column('u_department_Shift_2', sa.Integer(), nullable=True),
    sa.Column('u_department_Shift_3', sa.Integer(), nullable=True),
    sa.Column('u_department_Shift_4', sa.Integer(), nullable=True),
    sa.Column('u_department_Trouble_Shooting', sa.Integer(), nullable=True),
    sa.Column('u_unit_B2B_Area', sa.Integer(), nullable=True),
    sa.Column('u_unit_Inventarization_Area', sa.Integer(), nullable=True),
    sa.Column('u_unit_Loading_Area', sa.Integer(), nullable=True),
    sa.Column('u_unit_New_Arrivals_Area', sa.Integer(), nullable=True),
    sa.Column('u_unit_Pack_Item_Area', sa.Integer(), nullable=True),
    sa.Column('u_unit_Packing_Area', sa.Integer(), nullable=True),
    sa.Column('u_unit_Picking_Area', sa.Integer(), nullable=True),
    sa.Column('u_unit_Putaway_Area', sa.Integer(), nullable=True),
    sa.Column('u_unit_Return_Area', sa.Integer(), nullable=True),
    sa.Column('u_unit_Sorting_Area', sa.Integer(), nullable=True),
    sa.Column('u_unit_Trouble_Area', sa.Integer(), nullable=True),
    sa.Column('u_unit_Unpacking_Area', sa.Integer(), nullable=True),
    sa.Column('e_source_superjob', sa.Integer(), nullable=True),
    sa.Column('e_position_eng_DC_employee', sa.Integer(), nullable=True),
    sa.Column('e_position_eng_Leading_DC_employee', sa.Integer(), nullable=True),
    sa.Column('e_position_eng_Senior_DC_employee', sa.Integer(), nullable=True),
    sa.Column('e_source_headhunter', sa.Integer(), nullable=True),
    sa.Column('e_source_job_mo', sa.Integer(), nullable=True),
    sa.Column('e_source_lamoda', sa.Integer(), nullable=True),
    sa.Column('e_source_other', sa.Integer(), nullable=True),
    sa.Column('e_source_rabota', sa.Integer(), nullable=True),
    sa.Column('e_source_ref', sa.Integer(), nullable=True),
    sa.Column('e_source_zarplata', sa.Integer(), nullable=True),
    sa.Column('p_success_probability', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['e_id'], ['candidates.e_id'], ),
    sa.PrimaryKeyConstraint('p_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_predictions')
    op.drop_table('recruiters')
    op.drop_table('candidates')
    # ### end Alembic commands ###
