"""extended data from model

Revision ID: 8677331247e0
Revises: 0b69e6a1fd70
Create Date: 2019-02-02 15:57:18.893018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8677331247e0'
down_revision = '0b69e6a1fd70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_predictions', sa.Column('e_date_entered', sa.String(length=255), nullable=True))
    op.add_column('candidate_predictions', sa.Column('e_name', sa.String(length=255), nullable=True))
    op.add_column('candidate_predictions', sa.Column('e_recruiter', sa.String(length=255), nullable=True))
    op.add_column('candidate_predictions', sa.Column('e_start_day', sa.Integer(), nullable=True))
    op.add_column('candidate_predictions', sa.Column('e_start_month', sa.Integer(), nullable=True))
    op.add_column('candidate_predictions', sa.Column('e_start_weekday', sa.Integer(), nullable=True))
    op.add_column('candidate_predictions', sa.Column('e_start_year', sa.Integer(), nullable=True))
    op.add_column('candidate_predictions', sa.Column('r_id', sa.String(length=255), nullable=True))
    op.add_column('candidate_predictions', sa.Column('u_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_predictions', 'u_id')
    op.drop_column('candidate_predictions', 'r_id')
    op.drop_column('candidate_predictions', 'e_start_year')
    op.drop_column('candidate_predictions', 'e_start_weekday')
    op.drop_column('candidate_predictions', 'e_start_month')
    op.drop_column('candidate_predictions', 'e_start_day')
    op.drop_column('candidate_predictions', 'e_recruiter')
    op.drop_column('candidate_predictions', 'e_name')
    op.drop_column('candidate_predictions', 'e_date_entered')
    # ### end Alembic commands ###
