"""first migration

Revision ID: ed9ffed5b075
Revises: 
Create Date: 2019-01-29 11:42:14.807062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed9ffed5b075'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('e_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('e_name', sa.String(length=255), nullable=True),
    sa.Column('e_age', sa.Integer(), nullable=True),
    sa.Column('e_gender', sa.Integer(), nullable=True),
    sa.Column('e_recomended', sa.Integer(), nullable=True),
    sa.Column('e_position_eng', sa.String(length=255), nullable=True),
    sa.Column('e_salary_base', sa.Integer(), nullable=True),
    sa.Column('e_recruiter', sa.String(length=255), nullable=True),
    sa.Column('e_days_to_hire', sa.Integer(), nullable=True),
    sa.Column('e_commute', sa.Float(), nullable=True),
    sa.Column('e_entrance_type', sa.Integer(), nullable=True),
    sa.Column('e_source', sa.String(length=255), nullable=True),
    sa.Column('e_date_entered', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('e_id')
    )
    op.create_table('candidate_predictions',
    sa.Column('p_id', sa.Integer(), nullable=False),
    sa.Column('p_date', sa.DateTime(), nullable=False),
    sa.Column('e_recruiter', sa.String(length=255), nullable=True),
    sa.Column('e_id', sa.Integer(), nullable=False),
    sa.Column('e_age', sa.Integer(), nullable=True),
    sa.Column('e_gender', sa.Integer(), nullable=True),
    sa.Column('e_position_eng', sa.String(length=255), nullable=True),
    sa.Column('e_entrance_type', sa.Integer(), nullable=True),
    sa.Column('e_source', sa.String(length=255), nullable=True),
    sa.Column('e_days_to_hire', sa.Integer(), nullable=True),
    sa.Column('e_recomended', sa.Integer(), nullable=True),
    sa.Column('e_salary_base', sa.Integer(), nullable=True),
    sa.Column('e_commute', sa.Float(), nullable=True),
    sa.Column('r_age', sa.Integer(), nullable=True),
    sa.Column('r_tenure', sa.Integer(), nullable=True),
    sa.Column('r_level', sa.Integer(), nullable=True),
    sa.Column('u_department', sa.String(length=255), nullable=True),
    sa.Column('u_unit', sa.String(length=255), nullable=True),
    sa.Column('u_ntt', sa.Integer(), nullable=True),
    sa.Column('u_tl_tenure', sa.Integer(), nullable=True),
    sa.Column('u_tl_age', sa.Integer(), nullable=True),
    sa.Column('u_tl_gender', sa.Integer(), nullable=True),
    sa.Column('u_hires_week', sa.Integer(), nullable=True),
    sa.Column('u_exits_week', sa.Integer(), nullable=True),
    sa.Column('u_hires_month', sa.Integer(), nullable=True),
    sa.Column('u_exits_month', sa.Integer(), nullable=True),
    sa.Column('u_headcount', sa.Integer(), nullable=True),
    sa.Column('u_age_mean', sa.Float(), nullable=True),
    sa.Column('u_tenure_mean', sa.Float(), nullable=True),
    sa.Column('u_gender_average', sa.Float(), nullable=True),
    sa.Column('u_tl_active', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['e_id'], ['candidates.e_id'], ),
    sa.PrimaryKeyConstraint('p_id')
    )
    op.drop_table('initial_data')
    op.drop_table('units')
    op.drop_table('recruiters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruiters',
    sa.Column('e_recruiter', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('r_age', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('r_tenure', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('r_level', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('units',
    sa.Column('e_unit', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('u_department', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('u_unit', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('u_ntt', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('u_tl_tenure', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('u_tl_age', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('u_tl_gender', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('u_hires_week', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('u_exits_week', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('u_hires_month', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('u_exits_month', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('u_headcount', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('u_age_mean', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('u_tenure_mean', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('u_gender_average', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('u_tl_active', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('initial_data',
    sa.Column('e_employee_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('e_position_eng', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('e_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('e_salary_base', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('e_quit_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('u_department', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('u_unit', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('u_ntt', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('e_age', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('e_gender', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('u_tl_tenure', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('u_tl_age', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('u_tl_exit', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('u_tl_gender', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('u_hires_week', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('u_exits_week', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('u_hires_month', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('u_exits_month', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('u_headcount', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('u_age_mean', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('u_age_median', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('u_tenure_mean', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('u_tenure_median', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('u_gender_average', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('e_entrance_type', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('e_salary_desired', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('e_source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('e_days_to_hire', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('e_recomended', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('r_age', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('r_tenure', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('r_level', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('u_tl_active', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('e_commute', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('e_tenure_final', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('e_include', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('e_probation', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.drop_table('candidate_predictions')
    op.drop_table('candidates')
    # ### end Alembic commands ###
